# Generated by Django 4.1.1 on 2022-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliakspaul", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="career",
            field=models.CharField(max_length=50),
        ),
    ]
