# Generated by Django 4.1.1 on 2022-10-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliakspaul", "0002_alter_about_career"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skill_name",
            field=models.CharField(max_length=50),
        ),
    ]
