# Generated by Django 4.1.1 on 2022-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliakspaul", "0003_alter_skills_skill_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="name",
            field=models.CharField(default="Portfolio", max_length=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="greeting_1",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="home",
            name="greeting_2",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="home",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
