# Generated by Django 4.1.1 on 2022-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliakspaul", "0004_portfolio_name_alter_home_greeting_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=70, unique=True)),
                ("phone", models.CharField(max_length=200)),
                ("adress", models.CharField(max_length=200)),
            ],
        ),
    ]
