# Generated by Django 4.1.1 on 2022-10-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliakspaul", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="adress",
            field=models.CharField(default="-", max_length=200),
        ),
        migrations.AddField(
            model_name="about",
            name="email",
            field=models.EmailField(
                blank=True, default="-", max_length=70, unique=True
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="phone",
            field=models.CharField(default="-", max_length=200),
        ),
    ]
